In [1]:
import numpy as np
import pandas as pd

df = pd.DataFrame(
    np.random.randint(0, 100, size=(100, 4)),
    columns=list('ABCD'),
)

df

     A   B   C   D
0   86  22  94  44
1    6  49  32  81
2    6   3  63   9
3   12   1  26  68
4   23  84  89  36
..  ..  ..  ..  ..
95  19  51   7  74
96  72  61  45  42
97  89  42  20  17
98  68  92  39  29
99  48  96  53  67

[100 rows x 4 columns]